<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'numeropiece', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nomclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'telclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'adressclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'mailclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'reservation', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'contrat'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'numeropiece', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'nomclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'telclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'adressclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'mailclient', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'reservation', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'contrat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeropiece(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeropiece', []);

        return parent::getNumeropiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeropiece(string $numeropiece): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeropiece', [$numeropiece]);

        return parent::setNumeropiece($numeropiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomclient(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomclient', []);

        return parent::getNomclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomclient(string $nomclient): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomclient', [$nomclient]);

        return parent::setNomclient($nomclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelclient(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelclient', []);

        return parent::getTelclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelclient(int $telclient): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelclient', [$telclient]);

        return parent::setTelclient($telclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressclient(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressclient', []);

        return parent::getAdressclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressclient(string $adressclient): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressclient', [$adressclient]);

        return parent::setAdressclient($adressclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailclient(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailclient', []);

        return parent::getMailclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailclient(string $mailclient): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailclient', [$mailclient]);

        return parent::setMailclient($mailclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

}
