<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUiOTxUD\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUiOTxUD/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUiOTxUD.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUiOTxUD\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUiOTxUD\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UiOTxUD',
    'container.build_id' => '7fc62161',
    'container.build_time' => 1523633897,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUiOTxUD');
