<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3DxS3bU\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3DxS3bU/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3DxS3bU.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3DxS3bU\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container3DxS3bU\srcDevDebugProjectContainer(array(
    'container.build_hash' => '3DxS3bU',
    'container.build_id' => 'f3d166cd',
    'container.build_time' => 1523436829,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3DxS3bU');
