<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTBmFEEg\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTBmFEEg/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTBmFEEg.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTBmFEEg\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTBmFEEg\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TBmFEEg',
    'container.build_id' => '13dcb418',
    'container.build_time' => 1524735350,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTBmFEEg');
